### ISSUE TITLE
graceful.shutdown.wait does not work when stopping the docker container

### ISSUE THREAD

**Issue by konstantinblaesi** [timpeeters/spring-boot-graceful-shutdown#155]
`docker stop app` will not trigger [this branch](https://github.com/timpeeters/spring-boot-graceful-shutdown/blob/master/src/main/java/com/github/timpeeters/boot/shutdown/autoconfigure/GracefulShutdownHealthIndicator.java#L35)
With the spring boot actuator for `/actuator/shutdown` enabled a
`curl -X POST http://localhost:8080/actuator/shutdown` will trigger it.

For testing purposes I just enabled all actuator endpoints using environment variable `MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*`

Is there a good reason to [trigger this](https://github.com/timpeeters/spring-boot-graceful-shutdown/blob/master/src/main/java/com/github/timpeeters/boot/shutdown/autoconfigure/GracefulShutdownHealthIndicator.java#L34) only for local context close events? When the spring boot app is run using docker, docker-compose, kubernetes, cloud foundry or whatever else you'd start/stop containers using the platforms tools and not call some spring endpoint to make it shutdown?
Would you advise to 
```
curl -X POST http://localhost:8080/actuator/shutdown
docker stop app
```
instead?

Or should I register a SIGTERM handler and trigger the context close event locally?
Why would you only trigger the out of service on the health endpoint if the shutdown event was triggered locally?

**Comment by konstantinblaesi** [comment]
Never mind. Everything seems to work as expected so far, the issue was configuration related. I set
```
graceful.shutdown.timeout=60
graceful.shutdown.wait=30
```
in application.properties instead of
```
graceful.shutdown.timeout=60s
graceful.shutdown.wait=30s
```
The former caused the units of timeout and wait to be milliseconds instead of seconds and apparently I got confused debugging and mistakenly concluded that the graceful shutdown logic would not be triggerd.
I think the [configuration documentation](https://github.com/timpeeters/spring-boot-graceful-shutdown#configuration) could be extended to be more explicit regarding the units what do you think?

**Comment by timpeeters** [comment]
Thanks for the PR.
