### ISSUE TITLE
需要考虑等待其它线程池被关闭

### ISSUE THREAD

**Issue by ClayGminx** [timpeeters/spring-boot-graceful-shutdown#560]
你好，我已经使用了你的程序，我觉得这是众多优雅停机程序中最好用的一个。然而，在实际使用时，还是未能完全满足需求。比如，我的程序在优雅停机时，还需要等待`@Async`线程池，和从Apache Curator来的`PathChildCache`的监听器线程池。为了满足需求，建议修改`GracefulShutdownTomcatConnectorCustomizer`中的`shutdownThreadPoolExecutor()`方法，获取每一个需要被关闭的线程池。

**Comment by timpeeters** [comment]
Correct, the scope of this project was to provide graceful shutdown for the **web container** embedded in Spring Boot. 

However I believe you can easily achieve graceful shutdown of custom thread pools in Spring Boot without any additional library.

E.g.

```
@Bean
public TaskExecutor taskExecutor() {
    ThreadPoolTaskExecutor taskExecutor = new ThreadPoolTaskExecutor();
    taskExecutor.setAwaitTerminationSeconds(10);
    taskExecutor.setWaitForTasksToCompleteOnShutdown(true);
    taskExecutor.initialize();

    return taskExecutor;
}
```

You can then use this custom thread pool for your @Async methods (or customize the default thread pool in Spring Boot).

**Comment by timpeeters** [comment]
There are already some out-of-the-box Spring Boot properties you can use to configure the default thread pools:

```
spring.task.executor.*
spring.task.scheduling.*
```

**Comment by ClayGminx** [comment]
Thanks. I have already used your codes in my app. And thank you for reading my issue in Chinese.
